# Generated by Django 5.0.1 on 2025-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('market_demand', models.CharField(max_length=20)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_rainfall', models.FloatField()),
                ('max_rainfall', models.FloatField()),
                ('ideal_soil_ph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_crop', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
